name: Test
on:
  push:
    branches-ignore:
      - master

jobs:
  test_client:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.3.x]

    steps:
      - uses: actions/checkout@v2.3.4

      - uses: actions/cache@v2
        with:
          path: |
            client/node_modules
            client/package-lock.json
          key: ${{ runner.os }}-modules-${{ hashFiles('client/package.json') }}

      - name: Configurando node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm install
        run: |
          cd client && npm install

      - name: test
        run: |
          cd client && npm run test && npm run build

  test_server:
     runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.3.x]

    steps:
      - uses: actions/checkout@v2.3.4

      - uses: actions/cache@v2
        with:
          path: |
            server/node_modules
            server/package-lock.json
          key: ${{ runner.os }}-modules-${{ hashFiles('server/package.json') }}

      - name: Configurando node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm install
        run: |
          cd server && npm install

      - name: test
        run: |
          cd server && npm run build